spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.dmmdgekpwabkaitjwgkr&password=[YOUR-PASSWORD]
    username: postgres
    password: Ma060507@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: 10.11.0.37
    port: 5672
    username: admin
    password: visioncontrolrabbit
    virtual-host: /