spring:
  application:
    name: telemetria

  datasource:
    url: jdbc:postgresql://postgres-mensageria:5432/mensageria
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /

# Variáveis customizadas que o @Value irá ler na sua classe RabbitMQConfig
rabbitmq:
  queue:
    name: visioncontrol_queue
  exchange:
    name: telemetria.exchange  # AQUI ESTÁ A CORREÇÃO DO SEU ERRO 404!
  routingkey:
    name: telemetria.routingkey