spring.application.name=telemetria

rabbitmq.queue.name=visioncontrol_queue
rabbitmq.exchange.name=exchange
rabbitmq.routingkey.name=routingkey

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/visioncontrol}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0605}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect