spring:
  main:
    web-application-type: servlet

  datasource:
    url: "jdbc:postgresql://localhost:5432/torredecontrole"
    username: "postgres"
    password: "0605"
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: VisionControlHikariPool
      maximum-pool-size: 15
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true

  rabbitmq:
    host: 82.29.61.141
    port: 5672
    username: "admin"
    password: "visioncontrolrabbit"
    virtual-host: /
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 50

app:
  rabbitmq:
    queue: "fila-visioncontrol-prod"
    exchange: "visioncontrol-exchange"
    routing-key: "visioncontrol.routing.key"
    dlq-queue: "fila-visioncontrol-prod-dlq"

server:
  port: 8080
  tomcat:
    basedir: ./.tomcat